### ISSUE TITLE
release a new version to allow the download via ansible-galaxy

### ISSUE THREAD

**Issue by lynxis** [Yannik/ansible-role-letsencrypt#2]
Please release a new version on galaxy so it can be downloaded.

<code>
# ansible-galaxy install Yannik.letsencrypt 
- downloading role 'letsencrypt', owned by Yannik
- downloading role from https://github.com/Yannik/ansible-role-letsencrypt/archive/v1.0.0.tar.gz
 [WARNING]: - Yannik.letsencrypt was NOT installed successfully: this role does not appear to have a meta/main.yml file.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
</.code

**Comment by Yannik** [comment]
done!
